use super::ColorU8;

/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: rgba(0,0,0,0);"></div>
pub const TRANSPARENT: ColorU8 = ColorU8::from_rgba(0, 0, 0, 0);

// standard CSS colors
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #000000;"></div>
pub const BLACK: ColorU8 = ColorU8::from_html(b"#000000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #c0c0c0;"></div>
pub const SILVER: ColorU8 = ColorU8::from_html(b"#c0c0c0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #808080;"></div>
pub const GRAY: ColorU8 = ColorU8::from_html(b"#808080");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffffff;"></div>
pub const WHITE: ColorU8 = ColorU8::from_html(b"#ffffff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #800000;"></div>
pub const MAROON: ColorU8 = ColorU8::from_html(b"#800000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff0000;"></div>
pub const RED: ColorU8 = ColorU8::from_html(b"#ff0000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #800080;"></div>
pub const PURPLE: ColorU8 = ColorU8::from_html(b"#800080");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff00ff;"></div>
pub const FUCHSIA: ColorU8 = ColorU8::from_html(b"#ff00ff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #008000;"></div>
pub const GREEN: ColorU8 = ColorU8::from_html(b"#008000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00ff00;"></div>
pub const LIME: ColorU8 = ColorU8::from_html(b"#00ff00");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #808000;"></div>
pub const OLIVE: ColorU8 = ColorU8::from_html(b"#808000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffff00;"></div>
pub const YELLOW: ColorU8 = ColorU8::from_html(b"#ffff00");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #000080;"></div>
pub const NAVY: ColorU8 = ColorU8::from_html(b"#000080");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #0000ff;"></div>
pub const BLUE: ColorU8 = ColorU8::from_html(b"#0000ff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #008080;"></div>
pub const TEAL: ColorU8 = ColorU8::from_html(b"#008080");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00ffff;"></div>
pub const AQUA: ColorU8 = ColorU8::from_html(b"#00ffff");

// other named colors
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f0f8ff;"></div>
pub const ALICEBLUE: ColorU8 = ColorU8::from_html(b"#f0f8ff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #faebd7;"></div>
pub const ANTIQUEWHITE: ColorU8 = ColorU8::from_html(b"#faebd7");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #7fffd4;"></div>
pub const AQUAMARINE: ColorU8 = ColorU8::from_html(b"#7fffd4");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f0ffff;"></div>
pub const AZURE: ColorU8 = ColorU8::from_html(b"#f0ffff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f5f5dc;"></div>
pub const BEIGE: ColorU8 = ColorU8::from_html(b"#f5f5dc");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffe4c4;"></div>
pub const BISQUE: ColorU8 = ColorU8::from_html(b"#ffe4c4");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffebcd;"></div>
pub const BLANCHEDALMOND: ColorU8 = ColorU8::from_html(b"#ffebcd");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #8a2be2;"></div>
pub const BLUEVIOLET: ColorU8 = ColorU8::from_html(b"#8a2be2");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #a52a2a;"></div>
pub const BROWN: ColorU8 = ColorU8::from_html(b"#a52a2a");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #deb887;"></div>
pub const BURLYWOOD: ColorU8 = ColorU8::from_html(b"#deb887");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #5f9ea0;"></div>
pub const CADETBLUE: ColorU8 = ColorU8::from_html(b"#5f9ea0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #7fff00;"></div>
pub const CHARTREUSE: ColorU8 = ColorU8::from_html(b"#7fff00");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #d2691e;"></div>
pub const CHOCOLATE: ColorU8 = ColorU8::from_html(b"#d2691e");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff7f50;"></div>
pub const CORAL: ColorU8 = ColorU8::from_html(b"#ff7f50");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #6495ed;"></div>
pub const CORNFLOWERBLUE: ColorU8 = ColorU8::from_html(b"#6495ed");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fff8dc;"></div>
pub const CORNSILK: ColorU8 = ColorU8::from_html(b"#fff8dc");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #dc143c;"></div>
pub const CRIMSON: ColorU8 = ColorU8::from_html(b"#dc143c");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00ffff;"></div>
pub const CYAN: ColorU8 = AQUA;
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00008b;"></div>
pub const DARKBLUE: ColorU8 = ColorU8::from_html(b"#00008b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #008b8b;"></div>
pub const DARKCYAN: ColorU8 = ColorU8::from_html(b"#008b8b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #b8860b;"></div>
pub const DARKGOLDENROD: ColorU8 = ColorU8::from_html(b"#b8860b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #a9a9a9;"></div>
pub const DARKGRAY: ColorU8 = ColorU8::from_html(b"#a9a9a9");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #006400;"></div>
pub const DARKGREEN: ColorU8 = ColorU8::from_html(b"#006400");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #a9a9a9;"></div>
pub const DARKGREY: ColorU8 = ColorU8::from_html(b"#a9a9a9");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #bdb76b;"></div>
pub const DARKKHAKI: ColorU8 = ColorU8::from_html(b"#bdb76b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #8b008b;"></div>
pub const DARKMAGENTA: ColorU8 = ColorU8::from_html(b"#8b008b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #556b2f;"></div>
pub const DARKOLIVEGREEN: ColorU8 = ColorU8::from_html(b"#556b2f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff8c00;"></div>
pub const DARKORANGE: ColorU8 = ColorU8::from_html(b"#ff8c00");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #9932cc;"></div>
pub const DARKORCHID: ColorU8 = ColorU8::from_html(b"#9932cc");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #8b0000;"></div>
pub const DARKRED: ColorU8 = ColorU8::from_html(b"#8b0000");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #e9967a;"></div>
pub const DARKSALMON: ColorU8 = ColorU8::from_html(b"#e9967a");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #8fbc8f;"></div>
pub const DARKSEAGREEN: ColorU8 = ColorU8::from_html(b"#8fbc8f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #483d8b;"></div>
pub const DARKSLATEBLUE: ColorU8 = ColorU8::from_html(b"#483d8b");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #2f4f4f;"></div>
pub const DARKSLATEGRAY: ColorU8 = ColorU8::from_html(b"#2f4f4f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #2f4f4f;"></div>
pub const DARKSLATEGREY: ColorU8 = ColorU8::from_html(b"#2f4f4f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00ced1;"></div>
pub const DARKTURQUOISE: ColorU8 = ColorU8::from_html(b"#00ced1");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #9400d3;"></div>
pub const DARKVIOLET: ColorU8 = ColorU8::from_html(b"#9400d3");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff1493;"></div>
pub const DEEPPINK: ColorU8 = ColorU8::from_html(b"#ff1493");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00bfff;"></div>
pub const DEEPSKYBLUE: ColorU8 = ColorU8::from_html(b"#00bfff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #696969;"></div>
pub const DIMGRAY: ColorU8 = ColorU8::from_html(b"#696969");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #696969;"></div>
pub const DIMGREY: ColorU8 = ColorU8::from_html(b"#696969");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #1e90ff;"></div>
pub const DODGERBLUE: ColorU8 = ColorU8::from_html(b"#1e90ff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #b22222;"></div>
pub const FIREBRICK: ColorU8 = ColorU8::from_html(b"#b22222");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fffaf0;"></div>
pub const FLORALWHITE: ColorU8 = ColorU8::from_html(b"#fffaf0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #228b22;"></div>
pub const FORESTGREEN: ColorU8 = ColorU8::from_html(b"#228b22");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #dcdcdc;"></div>
pub const GAINSBORO: ColorU8 = ColorU8::from_html(b"#dcdcdc");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f8f8ff;"></div>
pub const GHOSTWHITE: ColorU8 = ColorU8::from_html(b"#f8f8ff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffd700;"></div>
pub const GOLD: ColorU8 = ColorU8::from_html(b"#ffd700");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #daa520;"></div>
pub const GOLDENROD: ColorU8 = ColorU8::from_html(b"#daa520");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #adff2f;"></div>
pub const GREENYELLOW: ColorU8 = ColorU8::from_html(b"#adff2f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #808080;"></div>
pub const GREY: ColorU8 = GRAY;
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f0fff0;"></div>
pub const HONEYDEW: ColorU8 = ColorU8::from_html(b"#f0fff0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff69b4;"></div>
pub const HOTPINK: ColorU8 = ColorU8::from_html(b"#ff69b4");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #cd5c5c;"></div>
pub const INDIANRED: ColorU8 = ColorU8::from_html(b"#cd5c5c");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #4b0082;"></div>
pub const INDIGO: ColorU8 = ColorU8::from_html(b"#4b0082");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fffff0;"></div>
pub const IVORY: ColorU8 = ColorU8::from_html(b"#fffff0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f0e68c;"></div>
pub const KHAKI: ColorU8 = ColorU8::from_html(b"#f0e68c");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #e6e6fa;"></div>
pub const LAVENDER: ColorU8 = ColorU8::from_html(b"#e6e6fa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fff0f5;"></div>
pub const LAVENDERBLUSH: ColorU8 = ColorU8::from_html(b"#fff0f5");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #7cfc00;"></div>
pub const LAWNGREEN: ColorU8 = ColorU8::from_html(b"#7cfc00");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fffacd;"></div>
pub const LEMONCHIFFON: ColorU8 = ColorU8::from_html(b"#fffacd");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #add8e6;"></div>
pub const LIGHTBLUE: ColorU8 = ColorU8::from_html(b"#add8e6");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f08080;"></div>
pub const LIGHTCORAL: ColorU8 = ColorU8::from_html(b"#f08080");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #e0ffff;"></div>
pub const LIGHTCYAN: ColorU8 = ColorU8::from_html(b"#e0ffff");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fafad2;"></div>
pub const LIGHTGOLDENRODYELLOW: ColorU8 = ColorU8::from_html(b"#fafad2");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #d3d3d3;"></div>
pub const LIGHTGRAY: ColorU8 = ColorU8::from_html(b"#d3d3d3");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #90ee90;"></div>
pub const LIGHTGREEN: ColorU8 = ColorU8::from_html(b"#90ee90");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #d3d3d3;"></div>
pub const LIGHTGREY: ColorU8 = ColorU8::from_html(b"#d3d3d3");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffb6c1;"></div>
pub const LIGHTPINK: ColorU8 = ColorU8::from_html(b"#ffb6c1");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffa07a;"></div>
pub const LIGHTSALMON: ColorU8 = ColorU8::from_html(b"#ffa07a");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #20b2aa;"></div>
pub const LIGHTSEAGREEN: ColorU8 = ColorU8::from_html(b"#20b2aa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #87cefa;"></div>
pub const LIGHTSKYBLUE: ColorU8 = ColorU8::from_html(b"#87cefa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #778899;"></div>
pub const LIGHTSLATEGRAY: ColorU8 = ColorU8::from_html(b"#778899");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #778899;"></div>
pub const LIGHTSLATEGREY: ColorU8 = ColorU8::from_html(b"#778899");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #b0c4de;"></div>
pub const LIGHTSTEELBLUE: ColorU8 = ColorU8::from_html(b"#b0c4de");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffffe0;"></div>
pub const LIGHTYELLOW: ColorU8 = ColorU8::from_html(b"#ffffe0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #32cd32;"></div>
pub const LIMEGREEN: ColorU8 = ColorU8::from_html(b"#32cd32");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #faf0e6;"></div>
pub const LINEN: ColorU8 = ColorU8::from_html(b"#faf0e6");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff00ff;"></div>
pub const MAGENTA: ColorU8 = FUCHSIA;
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #66cdaa;"></div>
pub const MEDIUMAQUAMARINE: ColorU8 = ColorU8::from_html(b"#66cdaa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #0000cd;"></div>
pub const MEDIUMBLUE: ColorU8 = ColorU8::from_html(b"#0000cd");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ba55d3;"></div>
pub const MEDIUMORCHID: ColorU8 = ColorU8::from_html(b"#ba55d3");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #9370db;"></div>
pub const MEDIUMPURPLE: ColorU8 = ColorU8::from_html(b"#9370db");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #3cb371;"></div>
pub const MEDIUMSEAGREEN: ColorU8 = ColorU8::from_html(b"#3cb371");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #7b68ee;"></div>
pub const MEDIUMSLATEBLUE: ColorU8 = ColorU8::from_html(b"#7b68ee");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00fa9a;"></div>
pub const MEDIUMSPRINGGREEN: ColorU8 = ColorU8::from_html(b"#00fa9a");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #48d1cc;"></div>
pub const MEDIUMTURQUOISE: ColorU8 = ColorU8::from_html(b"#48d1cc");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #c71585;"></div>
pub const MEDIUMVIOLETRED: ColorU8 = ColorU8::from_html(b"#c71585");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #191970;"></div>
pub const MIDNIGHTBLUE: ColorU8 = ColorU8::from_html(b"#191970");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f5fffa;"></div>
pub const MINTCREAM: ColorU8 = ColorU8::from_html(b"#f5fffa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffe4e1;"></div>
pub const MISTYROSE: ColorU8 = ColorU8::from_html(b"#ffe4e1");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffe4b5;"></div>
pub const MOCCASIN: ColorU8 = ColorU8::from_html(b"#ffe4b5");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffdead;"></div>
pub const NAVAJOWHITE: ColorU8 = ColorU8::from_html(b"#ffdead");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fdf5e6;"></div>
pub const OLDLACE: ColorU8 = ColorU8::from_html(b"#fdf5e6");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #6b8e23;"></div>
pub const OLIVEDRAB: ColorU8 = ColorU8::from_html(b"#6b8e23");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffa500;"></div>
pub const ORANGE: ColorU8 = ColorU8::from_html(b"#ffa500");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff4500;"></div>
pub const ORANGERED: ColorU8 = ColorU8::from_html(b"#ff4500");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #da70d6;"></div>
pub const ORCHID: ColorU8 = ColorU8::from_html(b"#da70d6");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #eee8aa;"></div>
pub const PALEGOLDENROD: ColorU8 = ColorU8::from_html(b"#eee8aa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #98fb98;"></div>
pub const PALEGREEN: ColorU8 = ColorU8::from_html(b"#98fb98");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #afeeee;"></div>
pub const PALETURQUOISE: ColorU8 = ColorU8::from_html(b"#afeeee");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #db7093;"></div>
pub const PALEVIOLETRED: ColorU8 = ColorU8::from_html(b"#db7093");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffefd5;"></div>
pub const PAPAYAWHIP: ColorU8 = ColorU8::from_html(b"#ffefd5");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffdab9;"></div>
pub const PEACHPUFF: ColorU8 = ColorU8::from_html(b"#ffdab9");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #cd853f;"></div>
pub const PERU: ColorU8 = ColorU8::from_html(b"#cd853f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ffc0cb;"></div>
pub const PINK: ColorU8 = ColorU8::from_html(b"#ffc0cb");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #dda0dd;"></div>
pub const PLUM: ColorU8 = ColorU8::from_html(b"#dda0dd");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #b0e0e6;"></div>
pub const POWDERBLUE: ColorU8 = ColorU8::from_html(b"#b0e0e6");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #663399;"></div>
pub const REBECCAPURPLE: ColorU8 = ColorU8::from_html(b"#663399");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #bc8f8f;"></div>
pub const ROSYBROWN: ColorU8 = ColorU8::from_html(b"#bc8f8f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #4169e1;"></div>
pub const ROYALBLUE: ColorU8 = ColorU8::from_html(b"#4169e1");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #8b4513;"></div>
pub const SADDLEBROWN: ColorU8 = ColorU8::from_html(b"#8b4513");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fa8072;"></div>
pub const SALMON: ColorU8 = ColorU8::from_html(b"#fa8072");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f4a460;"></div>
pub const SANDYBROWN: ColorU8 = ColorU8::from_html(b"#f4a460");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #2e8b57;"></div>
pub const SEAGREEN: ColorU8 = ColorU8::from_html(b"#2e8b57");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fff5ee;"></div>
pub const SEASHELL: ColorU8 = ColorU8::from_html(b"#fff5ee");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #a0522d;"></div>
pub const SIENNA: ColorU8 = ColorU8::from_html(b"#a0522d");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #87ceeb;"></div>
pub const SKYBLUE: ColorU8 = ColorU8::from_html(b"#87ceeb");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #6a5acd;"></div>
pub const SLATEBLUE: ColorU8 = ColorU8::from_html(b"#6a5acd");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #708090;"></div>
pub const SLATEGRAY: ColorU8 = ColorU8::from_html(b"#708090");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #708090;"></div>
pub const SLATEGREY: ColorU8 = ColorU8::from_html(b"#708090");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #fffafa;"></div>
pub const SNOW: ColorU8 = ColorU8::from_html(b"#fffafa");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #00ff7f;"></div>
pub const SPRINGGREEN: ColorU8 = ColorU8::from_html(b"#00ff7f");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #4682b4;"></div>
pub const STEELBLUE: ColorU8 = ColorU8::from_html(b"#4682b4");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #d2b48c;"></div>
pub const TAN: ColorU8 = ColorU8::from_html(b"#d2b48c");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #d8bfd8;"></div>
pub const THISTLE: ColorU8 = ColorU8::from_html(b"#d8bfd8");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ff6347;"></div>
pub const TOMATO: ColorU8 = ColorU8::from_html(b"#ff6347");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #40e0d0;"></div>
pub const TURQUOISE: ColorU8 = ColorU8::from_html(b"#40e0d0");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #ee82ee;"></div>
pub const VIOLET: ColorU8 = ColorU8::from_html(b"#ee82ee");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f5deb3;"></div>
pub const WHEAT: ColorU8 = ColorU8::from_html(b"#f5deb3");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #f5f5f5;"></div>
pub const WHITESMOKE: ColorU8 = ColorU8::from_html(b"#f5f5f5");
/// <div style="display: inline-block; width: 3em; height: 1em; border: 1px solid black; background: #9acd32;"></div>
pub const YELLOWGREEN: ColorU8 = ColorU8::from_html(b"#9acd32");

/// Lookup a named color (case-insensitive).
/// Return Some(ColorU8) if the name is known
pub(super) fn lookup_name(name: &str) -> Option<ColorU8> {
    match name.trim().to_ascii_lowercase().as_str() {
        "transparent" => Some(TRANSPARENT),
        "black" => Some(BLACK),
        "silver" => Some(SILVER),
        "gray" | "grey" => Some(GRAY),
        "white" => Some(WHITE),
        "maroon" => Some(MAROON),
        "red" => Some(RED),
        "purple" => Some(PURPLE),
        "fuchsia" => Some(FUCHSIA),
        "green" => Some(GREEN),
        "lime" => Some(LIME),
        "olive" => Some(OLIVE),
        "yellow" => Some(YELLOW),
        "navy" => Some(NAVY),
        "blue" => Some(BLUE),
        "teal" => Some(TEAL),
        "aqua" | "cyan" => Some(AQUA),

        "aliceblue" => Some(ALICEBLUE),
        "antiquewhite" => Some(ANTIQUEWHITE),
        "aquamarine" => Some(AQUAMARINE),
        "azure" => Some(AZURE),
        "beige" => Some(BEIGE),
        "bisque" => Some(BISQUE),
        "blanchedalmond" => Some(BLANCHEDALMOND),
        "blueviolet" => Some(BLUEVIOLET),
        "brown" => Some(BROWN),
        "burlywood" => Some(BURLYWOOD),
        "cadetblue" => Some(CADETBLUE),
        "chartreuse" => Some(CHARTREUSE),
        "chocolate" => Some(CHOCOLATE),
        "coral" => Some(CORAL),
        "cornflowerblue" => Some(CORNFLOWERBLUE),
        "cornsilk" => Some(CORNSILK),
        "crimson" => Some(CRIMSON),
        "darkblue" => Some(DARKBLUE),
        "darkcyan" => Some(DARKCYAN),
        "darkgoldenrod" => Some(DARKGOLDENROD),
        "darkgray" => Some(DARKGRAY),
        "darkgreen" => Some(DARKGREEN),
        "darkgrey" => Some(DARKGREY),
        "darkkhaki" => Some(DARKKHAKI),
        "darkmagenta" => Some(DARKMAGENTA),
        "darkolivegreen" => Some(DARKOLIVEGREEN),
        "darkorange" => Some(DARKORANGE),
        "darkorchid" => Some(DARKORCHID),
        "darkred" => Some(DARKRED),
        "darksalmon" => Some(DARKSALMON),
        "darkseagreen" => Some(DARKSEAGREEN),
        "darkslateblue" => Some(DARKSLATEBLUE),
        "darkslategray" => Some(DARKSLATEGRAY),
        "darkslategrey" => Some(DARKSLATEGREY),
        "darkturquoise" => Some(DARKTURQUOISE),
        "darkviolet" => Some(DARKVIOLET),
        "deeppink" => Some(DEEPPINK),
        "deepskyblue" => Some(DEEPSKYBLUE),
        "dimgray" => Some(DIMGRAY),
        "dimgrey" => Some(DIMGREY),
        "dodgerblue" => Some(DODGERBLUE),
        "firebrick" => Some(FIREBRICK),
        "floralwhite" => Some(FLORALWHITE),
        "forestgreen" => Some(FORESTGREEN),
        "gainsboro" => Some(GAINSBORO),
        "ghostwhite" => Some(GHOSTWHITE),
        "gold" => Some(GOLD),
        "goldenrod" => Some(GOLDENROD),
        "greenyellow" => Some(GREENYELLOW),
        "honeydew" => Some(HONEYDEW),
        "hotpink" => Some(HOTPINK),
        "indianred" => Some(INDIANRED),
        "indigo" => Some(INDIGO),
        "ivory" => Some(IVORY),
        "khaki" => Some(KHAKI),
        "lavender" => Some(LAVENDER),
        "lavenderblush" => Some(LAVENDERBLUSH),
        "lawngreen" => Some(LAWNGREEN),
        "lemonchiffon" => Some(LEMONCHIFFON),
        "lightblue" => Some(LIGHTBLUE),
        "lightcoral" => Some(LIGHTCORAL),
        "lightcyan" => Some(LIGHTCYAN),
        "lightgoldenrodyellow" => Some(LIGHTGOLDENRODYELLOW),
        "lightgray" => Some(LIGHTGRAY),
        "lightgreen" => Some(LIGHTGREEN),
        "lightgrey" => Some(LIGHTGREY),
        "lightpink" => Some(LIGHTPINK),
        "lightsalmon" => Some(LIGHTSALMON),
        "lightseagreen" => Some(LIGHTSEAGREEN),
        "lightskyblue" => Some(LIGHTSKYBLUE),
        "lightslategray" => Some(LIGHTSLATEGRAY),
        "lightslategrey" => Some(LIGHTSLATEGREY),
        "lightsteelblue" => Some(LIGHTSTEELBLUE),
        "lightyellow" => Some(LIGHTYELLOW),
        "limegreen" => Some(LIMEGREEN),
        "linen" => Some(LINEN),

        "magenta" => Some(MAGENTA),
        "mediumaquamarine" => Some(MEDIUMAQUAMARINE),
        "mediumblue" => Some(MEDIUMBLUE),
        "mediumorchid" => Some(MEDIUMORCHID),
        "mediumpurple" => Some(MEDIUMPURPLE),
        "mediumseagreen" => Some(MEDIUMSEAGREEN),
        "mediumslateblue" => Some(MEDIUMSLATEBLUE),
        "mediumspringgreen" => Some(MEDIUMSPRINGGREEN),
        "mediumturquoise" => Some(MEDIUMTURQUOISE),
        "mediumvioletred" => Some(MEDIUMVIOLETRED),
        "midnightblue" => Some(MIDNIGHTBLUE),
        "mintcream" => Some(MINTCREAM),
        "mistyrose" => Some(MISTYROSE),
        "moccasin" => Some(MOCCASIN),
        "navajowhite" => Some(NAVAJOWHITE),
        "oldlace" => Some(OLDLACE),
        "olivedrab" => Some(OLIVEDRAB),
        "orange" => Some(ORANGE),
        "orangered" => Some(ORANGERED),
        "orchid" => Some(ORCHID),
        "palegoldenrod" => Some(PALEGOLDENROD),
        "palegreen" => Some(PALEGREEN),
        "paleturquoise" => Some(PALETURQUOISE),
        "palevioletred" => Some(PALEVIOLETRED),
        "papayawhip" => Some(PAPAYAWHIP),
        "peachpuff" => Some(PEACHPUFF),
        "peru" => Some(PERU),
        "pink" => Some(PINK),
        "plum" => Some(PLUM),
        "powderblue" => Some(POWDERBLUE),
        "rebeccapurple" => Some(REBECCAPURPLE),
        "rosybrown" => Some(ROSYBROWN),
        "royalblue" => Some(ROYALBLUE),
        "saddlebrown" => Some(SADDLEBROWN),
        "salmon" => Some(SALMON),
        "sandybrown" => Some(SANDYBROWN),
        "seagreen" => Some(SEAGREEN),
        "seashell" => Some(SEASHELL),
        "sienna" => Some(SIENNA),
        "skyblue" => Some(SKYBLUE),
        "slateblue" => Some(SLATEBLUE),
        "slategray" => Some(SLATEGRAY),
        "slategrey" => Some(SLATEGREY),
        "snow" => Some(SNOW),
        "springgreen" => Some(SPRINGGREEN),
        "steelblue" => Some(STEELBLUE),
        "tan" => Some(TAN),
        "thistle" => Some(THISTLE),
        "tomato" => Some(TOMATO),
        "turquoise" => Some(TURQUOISE),
        "violet" => Some(VIOLET),
        "wheat" => Some(WHEAT),
        "whitesmoke" => Some(WHITESMOKE),
        "yellowgreen" => Some(YELLOWGREEN),

        _ => None,
    }
}
