use super::Rgba8;

/// Colors from the xkcd color survey, minus the colors that are present in the CSS4 color set.
/// These are not intended to be used directly, but are available for users who want to use them.
/// https://blog.xkcd.com/2010/05/03/color-survey-results/

pub const COLORS: &[(&str, Rgba8)] = &[
    ("cloudy blue", Rgba8::from_hex(b"#acc2d9")),
    ("dark pastel green", Rgba8::from_hex(b"#56ae57")),
    ("dust", Rgba8::from_hex(b"#b2996e")),
    ("electric lime", Rgba8::from_hex(b"#a8ff04")),
    ("fresh green", Rgba8::from_hex(b"#69d84f")),
    ("light eggplant", Rgba8::from_hex(b"#894585")),
    ("nasty green", Rgba8::from_hex(b"#70b23f")),
    ("really light blue", Rgba8::from_hex(b"#d4ffff")),
    ("tea", Rgba8::from_hex(b"#65ab7c")),
    ("warm purple", Rgba8::from_hex(b"#952e8f")),
    ("yellowish tan", Rgba8::from_hex(b"#fcfc81")),
    ("cement", Rgba8::from_hex(b"#a5a391")),
    ("dark grass green", Rgba8::from_hex(b"#388004")),
    ("dusty teal", Rgba8::from_hex(b"#4c9085")),
    ("grey teal", Rgba8::from_hex(b"#5e9b8a")),
    ("macaroni and cheese", Rgba8::from_hex(b"#efb435")),
    ("pinkish tan", Rgba8::from_hex(b"#d99b82")),
    ("spruce", Rgba8::from_hex(b"#0a5f38")),
    ("strong blue", Rgba8::from_hex(b"#0c06f7")),
    ("toxic green", Rgba8::from_hex(b"#61de2a")),
    ("windows blue", Rgba8::from_hex(b"#3778bf")),
    ("blue blue", Rgba8::from_hex(b"#2242c7")),
    ("blue with a hint of purple", Rgba8::from_hex(b"#533cc6")),
    ("booger", Rgba8::from_hex(b"#9bb53c")),
    ("bright sea green", Rgba8::from_hex(b"#05ffa6")),
    ("dark green blue", Rgba8::from_hex(b"#1f6357")),
    ("deep turquoise", Rgba8::from_hex(b"#017374")),
    ("green teal", Rgba8::from_hex(b"#0cb577")),
    ("strong pink", Rgba8::from_hex(b"#ff0789")),
    ("bland", Rgba8::from_hex(b"#afa88b")),
    ("deep aqua", Rgba8::from_hex(b"#08787f")),
    ("lavender pink", Rgba8::from_hex(b"#dd85d7")),
    ("light moss green", Rgba8::from_hex(b"#a6c875")),
    ("light seafoam green", Rgba8::from_hex(b"#a7ffb5")),
    ("olive yellow", Rgba8::from_hex(b"#c2b709")),
    ("pig pink", Rgba8::from_hex(b"#e78ea5")),
    ("deep lilac", Rgba8::from_hex(b"#966ebd")),
    ("desert", Rgba8::from_hex(b"#ccad60")),
    ("dusty lavender", Rgba8::from_hex(b"#ac86a8")),
    ("purpley grey", Rgba8::from_hex(b"#947e94")),
    ("purply", Rgba8::from_hex(b"#983fb2")),
    ("candy pink", Rgba8::from_hex(b"#ff63e9")),
    ("light pastel green", Rgba8::from_hex(b"#b2fba5")),
    ("boring green", Rgba8::from_hex(b"#63b365")),
    ("kiwi green", Rgba8::from_hex(b"#8ee53f")),
    ("light grey green", Rgba8::from_hex(b"#b7e1a1")),
    ("orange pink", Rgba8::from_hex(b"#ff6f52")),
    ("tea green", Rgba8::from_hex(b"#bdf8a3")),
    ("very light brown", Rgba8::from_hex(b"#d3b683")),
    ("egg shell", Rgba8::from_hex(b"#fffcc4")),
    ("eggplant purple", Rgba8::from_hex(b"#430541")),
    ("powder pink", Rgba8::from_hex(b"#ffb2d0")),
    ("reddish grey", Rgba8::from_hex(b"#997570")),
    ("baby shit brown", Rgba8::from_hex(b"#ad900d")),
    ("liliac", Rgba8::from_hex(b"#c48efd")),
    ("stormy blue", Rgba8::from_hex(b"#507b9c")),
    ("ugly brown", Rgba8::from_hex(b"#7d7103")),
    ("custard", Rgba8::from_hex(b"#fffd78")),
    ("darkish pink", Rgba8::from_hex(b"#da467d")),
    ("deep brown", Rgba8::from_hex(b"#410200")),
    ("greenish beige", Rgba8::from_hex(b"#c9d179")),
    ("manilla", Rgba8::from_hex(b"#fffa86")),
    ("off blue", Rgba8::from_hex(b"#5684ae")),
    ("battleship grey", Rgba8::from_hex(b"#6b7c85")),
    ("browny green", Rgba8::from_hex(b"#6f6c0a")),
    ("bruise", Rgba8::from_hex(b"#7e4071")),
    ("kelley green", Rgba8::from_hex(b"#009337")),
    ("sickly yellow", Rgba8::from_hex(b"#d0e429")),
    ("sunny yellow", Rgba8::from_hex(b"#fff917")),
    ("azul", Rgba8::from_hex(b"#1d5dec")),
    ("green/yellow", Rgba8::from_hex(b"#b5ce08")),
    ("lichen", Rgba8::from_hex(b"#8fb67b")),
    ("light light green", Rgba8::from_hex(b"#c8ffb0")),
    ("pale gold", Rgba8::from_hex(b"#fdde6c")),
    ("sun yellow", Rgba8::from_hex(b"#ffdf22")),
    ("tan green", Rgba8::from_hex(b"#a9be70")),
    ("burple", Rgba8::from_hex(b"#6832e3")),
    ("butterscotch", Rgba8::from_hex(b"#fdb147")),
    ("toupe", Rgba8::from_hex(b"#c7ac7d")),
    ("dark cream", Rgba8::from_hex(b"#fff39a")),
    ("indian red", Rgba8::from_hex(b"#850e04")),
    ("light lavendar", Rgba8::from_hex(b"#efc0fe")),
    ("poison green", Rgba8::from_hex(b"#40fd14")),
    ("baby puke green", Rgba8::from_hex(b"#b6c406")),
    ("bright yellow green", Rgba8::from_hex(b"#9dff00")),
    ("charcoal grey", Rgba8::from_hex(b"#3c4142")),
    ("squash", Rgba8::from_hex(b"#f2ab15")),
    ("cinnamon", Rgba8::from_hex(b"#ac4f06")),
    ("light pea green", Rgba8::from_hex(b"#c4fe82")),
    ("radioactive green", Rgba8::from_hex(b"#2cfa1f")),
    ("raw sienna", Rgba8::from_hex(b"#9a6200")),
    ("baby purple", Rgba8::from_hex(b"#ca9bf7")),
    ("cocoa", Rgba8::from_hex(b"#875f42")),
    ("light royal blue", Rgba8::from_hex(b"#3a2efe")),
    ("orangeish", Rgba8::from_hex(b"#fd8d49")),
    ("rust brown", Rgba8::from_hex(b"#8b3103")),
    ("sand brown", Rgba8::from_hex(b"#cba560")),
    ("swamp", Rgba8::from_hex(b"#698339")),
    ("tealish green", Rgba8::from_hex(b"#0cdc73")),
    ("burnt siena", Rgba8::from_hex(b"#b75203")),
    ("camo", Rgba8::from_hex(b"#7f8f4e")),
    ("dusk blue", Rgba8::from_hex(b"#26538d")),
    ("fern", Rgba8::from_hex(b"#63a950")),
    ("old rose", Rgba8::from_hex(b"#c87f89")),
    ("pale light green", Rgba8::from_hex(b"#b1fc99")),
    ("peachy pink", Rgba8::from_hex(b"#ff9a8a")),
    ("rosy pink", Rgba8::from_hex(b"#f6688e")),
    ("light bluish green", Rgba8::from_hex(b"#76fda8")),
    ("light bright green", Rgba8::from_hex(b"#53fe5c")),
    ("light neon green", Rgba8::from_hex(b"#4efd54")),
    ("light seafoam", Rgba8::from_hex(b"#a0febf")),
    ("tiffany blue", Rgba8::from_hex(b"#7bf2da")),
    ("washed out green", Rgba8::from_hex(b"#bcf5a6")),
    ("browny orange", Rgba8::from_hex(b"#ca6b02")),
    ("nice blue", Rgba8::from_hex(b"#107ab0")),
    ("sapphire", Rgba8::from_hex(b"#2138ab")),
    ("greyish teal", Rgba8::from_hex(b"#719f91")),
    ("orangey yellow", Rgba8::from_hex(b"#fdb915")),
    ("parchment", Rgba8::from_hex(b"#fefcaf")),
    ("straw", Rgba8::from_hex(b"#fcf679")),
    ("very dark brown", Rgba8::from_hex(b"#1d0200")),
    ("terracota", Rgba8::from_hex(b"#cb6843")),
    ("ugly blue", Rgba8::from_hex(b"#31668a")),
    ("clear blue", Rgba8::from_hex(b"#247afd")),
    ("creme", Rgba8::from_hex(b"#ffffb6")),
    ("foam green", Rgba8::from_hex(b"#90fda9")),
    ("grey/green", Rgba8::from_hex(b"#86a17d")),
    ("light gold", Rgba8::from_hex(b"#fddc5c")),
    ("seafoam blue", Rgba8::from_hex(b"#78d1b6")),
    ("topaz", Rgba8::from_hex(b"#13bbaf")),
    ("violet pink", Rgba8::from_hex(b"#fb5ffc")),
    ("wintergreen", Rgba8::from_hex(b"#20f986")),
    ("yellow tan", Rgba8::from_hex(b"#ffe36e")),
    ("dark fuchsia", Rgba8::from_hex(b"#9d0759")),
    ("indigo blue", Rgba8::from_hex(b"#3a18b1")),
    ("light yellowish green", Rgba8::from_hex(b"#c2ff89")),
    ("pale magenta", Rgba8::from_hex(b"#d767ad")),
    ("rich purple", Rgba8::from_hex(b"#720058")),
    ("sunflower yellow", Rgba8::from_hex(b"#ffda03")),
    ("green/blue", Rgba8::from_hex(b"#01c08d")),
    ("leather", Rgba8::from_hex(b"#ac7434")),
    ("racing green", Rgba8::from_hex(b"#014600")),
    ("vivid purple", Rgba8::from_hex(b"#9900fa")),
    ("dark royal blue", Rgba8::from_hex(b"#02066f")),
    ("hazel", Rgba8::from_hex(b"#8e7618")),
    ("muted pink", Rgba8::from_hex(b"#d1768f")),
    ("booger green", Rgba8::from_hex(b"#96b403")),
    ("canary", Rgba8::from_hex(b"#fdff63")),
    ("cool grey", Rgba8::from_hex(b"#95a3a6")),
    ("dark taupe", Rgba8::from_hex(b"#7f684e")),
    ("darkish purple", Rgba8::from_hex(b"#751973")),
    ("true green", Rgba8::from_hex(b"#089404")),
    ("coral pink", Rgba8::from_hex(b"#ff6163")),
    ("dark sage", Rgba8::from_hex(b"#598556")),
    ("dark slate blue", Rgba8::from_hex(b"#214761")),
    ("flat blue", Rgba8::from_hex(b"#3c73a8")),
    ("mushroom", Rgba8::from_hex(b"#ba9e88")),
    ("rich blue", Rgba8::from_hex(b"#021bf9")),
    ("dirty purple", Rgba8::from_hex(b"#734a65")),
    ("greenblue", Rgba8::from_hex(b"#23c48b")),
    ("icky green", Rgba8::from_hex(b"#8fae22")),
    ("light khaki", Rgba8::from_hex(b"#e6f2a2")),
    ("warm blue", Rgba8::from_hex(b"#4b57db")),
    ("dark hot pink", Rgba8::from_hex(b"#d90166")),
    ("deep sea blue", Rgba8::from_hex(b"#015482")),
    ("carmine", Rgba8::from_hex(b"#9d0216")),
    ("dark yellow green", Rgba8::from_hex(b"#728f02")),
    ("pale peach", Rgba8::from_hex(b"#ffe5ad")),
    ("plum purple", Rgba8::from_hex(b"#4e0550")),
    ("golden rod", Rgba8::from_hex(b"#f9bc08")),
    ("neon red", Rgba8::from_hex(b"#ff073a")),
    ("old pink", Rgba8::from_hex(b"#c77986")),
    ("very pale blue", Rgba8::from_hex(b"#d6fffe")),
    ("blood orange", Rgba8::from_hex(b"#fe4b03")),
    ("grapefruit", Rgba8::from_hex(b"#fd5956")),
    ("sand yellow", Rgba8::from_hex(b"#fce166")),
    ("clay brown", Rgba8::from_hex(b"#b2713d")),
    ("dark blue grey", Rgba8::from_hex(b"#1f3b4d")),
    ("flat green", Rgba8::from_hex(b"#699d4c")),
    ("light green blue", Rgba8::from_hex(b"#56fca2")),
    ("warm pink", Rgba8::from_hex(b"#fb5581")),
    ("dodger blue", Rgba8::from_hex(b"#3e82fc")),
    ("gross green", Rgba8::from_hex(b"#a0bf16")),
    ("ice", Rgba8::from_hex(b"#d6fffa")),
    ("metallic blue", Rgba8::from_hex(b"#4f738e")),
    ("pale salmon", Rgba8::from_hex(b"#ffb19a")),
    ("sap green", Rgba8::from_hex(b"#5c8b15")),
    ("algae", Rgba8::from_hex(b"#54ac68")),
    ("bluey grey", Rgba8::from_hex(b"#89a0b0")),
    ("greeny grey", Rgba8::from_hex(b"#7ea07a")),
    ("highlighter green", Rgba8::from_hex(b"#1bfc06")),
    ("light light blue", Rgba8::from_hex(b"#cafffb")),
    ("light mint", Rgba8::from_hex(b"#b6ffbb")),
    ("raw umber", Rgba8::from_hex(b"#a75e09")),
    ("vivid blue", Rgba8::from_hex(b"#152eff")),
    ("deep lavender", Rgba8::from_hex(b"#8d5eb7")),
    ("dull teal", Rgba8::from_hex(b"#5f9e8f")),
    ("light greenish blue", Rgba8::from_hex(b"#63f7b4")),
    ("mud green", Rgba8::from_hex(b"#606602")),
    ("pinky", Rgba8::from_hex(b"#fc86aa")),
    ("red wine", Rgba8::from_hex(b"#8c0034")),
    ("shit green", Rgba8::from_hex(b"#758000")),
    ("tan brown", Rgba8::from_hex(b"#ab7e4c")),
    ("rosa", Rgba8::from_hex(b"#fe86a4")),
    ("lipstick", Rgba8::from_hex(b"#d5174e")),
    ("pale mauve", Rgba8::from_hex(b"#fed0fc")),
    ("claret", Rgba8::from_hex(b"#680018")),
    ("dandelion", Rgba8::from_hex(b"#fedf08")),
    ("poop green", Rgba8::from_hex(b"#6f7c00")),
    ("ruby", Rgba8::from_hex(b"#ca0147")),
    ("dark", Rgba8::from_hex(b"#1b2431")),
    ("greenish turquoise", Rgba8::from_hex(b"#00fbb0")),
    ("pastel red", Rgba8::from_hex(b"#db5856")),
    ("piss yellow", Rgba8::from_hex(b"#ddd618")),
    ("bright cyan", Rgba8::from_hex(b"#41fdfe")),
    ("dark coral", Rgba8::from_hex(b"#cf524e")),
    ("algae green", Rgba8::from_hex(b"#21c36f")),
    ("darkish red", Rgba8::from_hex(b"#a90308")),
    ("reddy brown", Rgba8::from_hex(b"#6e1005")),
    ("blush pink", Rgba8::from_hex(b"#fe828c")),
    ("camouflage green", Rgba8::from_hex(b"#4b6113")),
    ("lawn green", Rgba8::from_hex(b"#4da409")),
    ("putty", Rgba8::from_hex(b"#beae8a")),
    ("vibrant blue", Rgba8::from_hex(b"#0339f8")),
    ("dark sand", Rgba8::from_hex(b"#a88f59")),
    ("purple/blue", Rgba8::from_hex(b"#5d21d0")),
    ("saffron", Rgba8::from_hex(b"#feb209")),
    ("twilight", Rgba8::from_hex(b"#4e518b")),
    ("warm brown", Rgba8::from_hex(b"#964e02")),
    ("bluegrey", Rgba8::from_hex(b"#85a3b2")),
    ("bubble gum pink", Rgba8::from_hex(b"#ff69af")),
    ("duck egg blue", Rgba8::from_hex(b"#c3fbf4")),
    ("greenish cyan", Rgba8::from_hex(b"#2afeb7")),
    ("petrol", Rgba8::from_hex(b"#005f6a")),
    ("royal", Rgba8::from_hex(b"#0c1793")),
    ("butter", Rgba8::from_hex(b"#ffff81")),
    ("dusty orange", Rgba8::from_hex(b"#f0833a")),
    ("off yellow", Rgba8::from_hex(b"#f1f33f")),
    ("pale olive green", Rgba8::from_hex(b"#b1d27b")),
    ("orangish", Rgba8::from_hex(b"#fc824a")),
    ("leaf", Rgba8::from_hex(b"#71aa34")),
    ("light blue grey", Rgba8::from_hex(b"#b7c9e2")),
    ("dried blood", Rgba8::from_hex(b"#4b0101")),
    ("lightish purple", Rgba8::from_hex(b"#a552e6")),
    ("rusty red", Rgba8::from_hex(b"#af2f0d")),
    ("lavender blue", Rgba8::from_hex(b"#8b88f8")),
    ("light grass green", Rgba8::from_hex(b"#9af764")),
    ("light mint green", Rgba8::from_hex(b"#a6fbb2")),
    ("sunflower", Rgba8::from_hex(b"#ffc512")),
    ("velvet", Rgba8::from_hex(b"#750851")),
    ("brick orange", Rgba8::from_hex(b"#c14a09")),
    ("lightish red", Rgba8::from_hex(b"#fe2f4a")),
    ("pure blue", Rgba8::from_hex(b"#0203e2")),
    ("twilight blue", Rgba8::from_hex(b"#0a437a")),
    ("violet red", Rgba8::from_hex(b"#a50055")),
    ("yellowy brown", Rgba8::from_hex(b"#ae8b0c")),
    ("carnation", Rgba8::from_hex(b"#fd798f")),
    ("muddy yellow", Rgba8::from_hex(b"#bfac05")),
    ("dark seafoam green", Rgba8::from_hex(b"#3eaf76")),
    ("deep rose", Rgba8::from_hex(b"#c74767")),
    ("dusty red", Rgba8::from_hex(b"#b9484e")),
    ("grey/blue", Rgba8::from_hex(b"#647d8e")),
    ("lemon lime", Rgba8::from_hex(b"#bffe28")),
    ("purple/pink", Rgba8::from_hex(b"#d725de")),
    ("brown yellow", Rgba8::from_hex(b"#b29705")),
    ("purple brown", Rgba8::from_hex(b"#673a3f")),
    ("wisteria", Rgba8::from_hex(b"#a87dc2")),
    ("banana yellow", Rgba8::from_hex(b"#fafe4b")),
    ("lipstick red", Rgba8::from_hex(b"#c0022f")),
    ("water blue", Rgba8::from_hex(b"#0e87cc")),
    ("brown grey", Rgba8::from_hex(b"#8d8468")),
    ("vibrant purple", Rgba8::from_hex(b"#ad03de")),
    ("baby green", Rgba8::from_hex(b"#8cff9e")),
    ("barf green", Rgba8::from_hex(b"#94ac02")),
    ("eggshell blue", Rgba8::from_hex(b"#c4fff7")),
    ("sandy yellow", Rgba8::from_hex(b"#fdee73")),
    ("cool green", Rgba8::from_hex(b"#33b864")),
    ("pale", Rgba8::from_hex(b"#fff9d0")),
    ("blue/grey", Rgba8::from_hex(b"#758da3")),
    ("hot magenta", Rgba8::from_hex(b"#f504c9")),
    ("greyblue", Rgba8::from_hex(b"#77a1b5")),
    ("purpley", Rgba8::from_hex(b"#8756e4")),
    ("baby shit green", Rgba8::from_hex(b"#889717")),
    ("brownish pink", Rgba8::from_hex(b"#c27e79")),
    ("dark aquamarine", Rgba8::from_hex(b"#017371")),
    ("diarrhea", Rgba8::from_hex(b"#9f8303")),
    ("light mustard", Rgba8::from_hex(b"#f7d560")),
    ("pale sky blue", Rgba8::from_hex(b"#bdf6fe")),
    ("turtle green", Rgba8::from_hex(b"#75b84f")),
    ("bright olive", Rgba8::from_hex(b"#9cbb04")),
    ("dark grey blue", Rgba8::from_hex(b"#29465b")),
    ("greeny brown", Rgba8::from_hex(b"#696006")),
    ("lemon green", Rgba8::from_hex(b"#adf802")),
    ("light periwinkle", Rgba8::from_hex(b"#c1c6fc")),
    ("seaweed green", Rgba8::from_hex(b"#35ad6b")),
    ("sunshine yellow", Rgba8::from_hex(b"#fffd37")),
    ("ugly purple", Rgba8::from_hex(b"#a442a0")),
    ("medium pink", Rgba8::from_hex(b"#f36196")),
    ("puke brown", Rgba8::from_hex(b"#947706")),
    ("very light pink", Rgba8::from_hex(b"#fff4f2")),
    ("viridian", Rgba8::from_hex(b"#1e9167")),
    ("bile", Rgba8::from_hex(b"#b5c306")),
    ("faded yellow", Rgba8::from_hex(b"#feff7f")),
    ("very pale green", Rgba8::from_hex(b"#cffdbc")),
    ("vibrant green", Rgba8::from_hex(b"#0add08")),
    ("bright lime", Rgba8::from_hex(b"#87fd05")),
    ("spearmint", Rgba8::from_hex(b"#1ef876")),
    ("light aquamarine", Rgba8::from_hex(b"#7bfdc7")),
    ("light sage", Rgba8::from_hex(b"#bcecac")),
    ("baby poo", Rgba8::from_hex(b"#ab9004")),
    ("dark seafoam", Rgba8::from_hex(b"#1fb57a")),
    ("deep teal", Rgba8::from_hex(b"#00555a")),
    ("heather", Rgba8::from_hex(b"#a484ac")),
    ("rust orange", Rgba8::from_hex(b"#c45508")),
    ("dirty blue", Rgba8::from_hex(b"#3f829d")),
    ("fern green", Rgba8::from_hex(b"#548d44")),
    ("bright lilac", Rgba8::from_hex(b"#c95efb")),
    ("weird green", Rgba8::from_hex(b"#3ae57f")),
    ("peacock blue", Rgba8::from_hex(b"#016795")),
    ("avocado green", Rgba8::from_hex(b"#87a922")),
    ("faded orange", Rgba8::from_hex(b"#f0944d")),
    ("grape purple", Rgba8::from_hex(b"#5d1451")),
    ("hot green", Rgba8::from_hex(b"#25ff29")),
    ("lime yellow", Rgba8::from_hex(b"#d0fe1d")),
    ("mango", Rgba8::from_hex(b"#ffa62b")),
    ("shamrock", Rgba8::from_hex(b"#01b44c")),
    ("bubblegum", Rgba8::from_hex(b"#ff6cb5")),
    ("purplish brown", Rgba8::from_hex(b"#6b4247")),
    ("vomit yellow", Rgba8::from_hex(b"#c7c10c")),
    ("pale cyan", Rgba8::from_hex(b"#b7fffa")),
    ("key lime", Rgba8::from_hex(b"#aeff6e")),
    ("tomato red", Rgba8::from_hex(b"#ec2d01")),
    ("merlot", Rgba8::from_hex(b"#730039")),
    ("night blue", Rgba8::from_hex(b"#040348")),
    ("purpleish pink", Rgba8::from_hex(b"#df4ec8")),
    ("apple", Rgba8::from_hex(b"#6ecb3c")),
    ("baby poop green", Rgba8::from_hex(b"#8f9805")),
    ("green apple", Rgba8::from_hex(b"#5edc1f")),
    ("heliotrope", Rgba8::from_hex(b"#d94ff5")),
    ("yellow/green", Rgba8::from_hex(b"#c8fd3d")),
    ("almost black", Rgba8::from_hex(b"#070d0d")),
    ("cool blue", Rgba8::from_hex(b"#4984b8")),
    ("leafy green", Rgba8::from_hex(b"#51b73b")),
    ("mustard brown", Rgba8::from_hex(b"#ac7e04")),
    ("dusk", Rgba8::from_hex(b"#4e5481")),
    ("dull brown", Rgba8::from_hex(b"#876e4b")),
    ("frog green", Rgba8::from_hex(b"#58bc08")),
    ("vivid green", Rgba8::from_hex(b"#2fef10")),
    ("bright light green", Rgba8::from_hex(b"#2dfe54")),
    ("fluro green", Rgba8::from_hex(b"#0aff02")),
    ("kiwi", Rgba8::from_hex(b"#9cef43")),
    ("seaweed", Rgba8::from_hex(b"#18d17b")),
    ("navy green", Rgba8::from_hex(b"#35530a")),
    ("ultramarine blue", Rgba8::from_hex(b"#1805db")),
    ("iris", Rgba8::from_hex(b"#6258c4")),
    ("pastel orange", Rgba8::from_hex(b"#ff964f")),
    ("yellowish orange", Rgba8::from_hex(b"#ffab0f")),
    ("perrywinkle", Rgba8::from_hex(b"#8f8ce7")),
    ("tealish", Rgba8::from_hex(b"#24bca8")),
    ("dark plum", Rgba8::from_hex(b"#3f012c")),
    ("pear", Rgba8::from_hex(b"#cbf85f")),
    ("pinkish orange", Rgba8::from_hex(b"#ff724c")),
    ("midnight purple", Rgba8::from_hex(b"#280137")),
    ("light urple", Rgba8::from_hex(b"#b36ff6")),
    ("dark mint", Rgba8::from_hex(b"#48c072")),
    ("greenish tan", Rgba8::from_hex(b"#bccb7a")),
    ("light burgundy", Rgba8::from_hex(b"#a8415b")),
    ("turquoise blue", Rgba8::from_hex(b"#06b1c4")),
    ("ugly pink", Rgba8::from_hex(b"#cd7584")),
    ("sandy", Rgba8::from_hex(b"#f1da7a")),
    ("electric pink", Rgba8::from_hex(b"#ff0490")),
    ("muted purple", Rgba8::from_hex(b"#805b87")),
    ("mid green", Rgba8::from_hex(b"#50a747")),
    ("greyish", Rgba8::from_hex(b"#a8a495")),
    ("neon yellow", Rgba8::from_hex(b"#cfff04")),
    ("banana", Rgba8::from_hex(b"#ffff7e")),
    ("carnation pink", Rgba8::from_hex(b"#ff7fa7")),
    ("sea", Rgba8::from_hex(b"#3c9992")),
    ("muddy brown", Rgba8::from_hex(b"#886806")),
    ("turquoise green", Rgba8::from_hex(b"#04f489")),
    ("buff", Rgba8::from_hex(b"#fef69e")),
    ("fawn", Rgba8::from_hex(b"#cfaf7b")),
    ("muted blue", Rgba8::from_hex(b"#3b719f")),
    ("pale rose", Rgba8::from_hex(b"#fdc1c5")),
    ("dark mint green", Rgba8::from_hex(b"#20c073")),
    ("amethyst", Rgba8::from_hex(b"#9b5fc0")),
    ("blue/green", Rgba8::from_hex(b"#0f9b8e")),
    ("chestnut", Rgba8::from_hex(b"#742802")),
    ("sick green", Rgba8::from_hex(b"#9db92c")),
    ("pea", Rgba8::from_hex(b"#a4bf20")),
    ("rusty orange", Rgba8::from_hex(b"#cd5909")),
    ("stone", Rgba8::from_hex(b"#ada587")),
    ("rose red", Rgba8::from_hex(b"#be013c")),
    ("pale aqua", Rgba8::from_hex(b"#b8ffeb")),
    ("deep orange", Rgba8::from_hex(b"#dc4d01")),
    ("earth", Rgba8::from_hex(b"#a2653e")),
    ("mossy green", Rgba8::from_hex(b"#638b27")),
    ("grassy green", Rgba8::from_hex(b"#419c03")),
    ("pale lime green", Rgba8::from_hex(b"#b1ff65")),
    ("light grey blue", Rgba8::from_hex(b"#9dbcd4")),
    ("pale grey", Rgba8::from_hex(b"#fdfdfe")),
    ("asparagus", Rgba8::from_hex(b"#77ab56")),
    ("blueberry", Rgba8::from_hex(b"#464196")),
    ("purple red", Rgba8::from_hex(b"#990147")),
    ("pale lime", Rgba8::from_hex(b"#befd73")),
    ("greenish teal", Rgba8::from_hex(b"#32bf84")),
    ("caramel", Rgba8::from_hex(b"#af6f09")),
    ("deep magenta", Rgba8::from_hex(b"#a0025c")),
    ("light peach", Rgba8::from_hex(b"#ffd8b1")),
    ("milk chocolate", Rgba8::from_hex(b"#7f4e1e")),
    ("ocher", Rgba8::from_hex(b"#bf9b0c")),
    ("off green", Rgba8::from_hex(b"#6ba353")),
    ("purply pink", Rgba8::from_hex(b"#f075e6")),
    ("dusky blue", Rgba8::from_hex(b"#475f94")),
    ("golden", Rgba8::from_hex(b"#f5bf03")),
    ("light beige", Rgba8::from_hex(b"#fffeb6")),
    ("butter yellow", Rgba8::from_hex(b"#fffd74")),
    ("dusky purple", Rgba8::from_hex(b"#895b7b")),
    ("french blue", Rgba8::from_hex(b"#436bad")),
    ("ugly yellow", Rgba8::from_hex(b"#d0c101")),
    ("greeny yellow", Rgba8::from_hex(b"#c6f808")),
    ("orangish red", Rgba8::from_hex(b"#f43605")),
    ("shamrock green", Rgba8::from_hex(b"#02c14d")),
    ("orangish brown", Rgba8::from_hex(b"#b25f03")),
    ("tree green", Rgba8::from_hex(b"#2a7e19")),
    ("deep violet", Rgba8::from_hex(b"#490648")),
    ("gunmetal", Rgba8::from_hex(b"#536267")),
    ("blue/purple", Rgba8::from_hex(b"#5a06ef")),
    ("cherry", Rgba8::from_hex(b"#cf0234")),
    ("sandy brown", Rgba8::from_hex(b"#c4a661")),
    ("warm grey", Rgba8::from_hex(b"#978a84")),
    ("dark indigo", Rgba8::from_hex(b"#1f0954")),
    ("midnight", Rgba8::from_hex(b"#03012d")),
    ("bluey green", Rgba8::from_hex(b"#2bb179")),
    ("grey pink", Rgba8::from_hex(b"#c3909b")),
    ("soft purple", Rgba8::from_hex(b"#a66fb5")),
    ("blood", Rgba8::from_hex(b"#770001")),
    ("brown red", Rgba8::from_hex(b"#922b05")),
    ("medium grey", Rgba8::from_hex(b"#7d7f7c")),
    ("berry", Rgba8::from_hex(b"#990f4b")),
    ("poo", Rgba8::from_hex(b"#8f7303")),
    ("purpley pink", Rgba8::from_hex(b"#c83cb9")),
    ("light salmon", Rgba8::from_hex(b"#fea993")),
    ("snot", Rgba8::from_hex(b"#acbb0d")),
    ("easter purple", Rgba8::from_hex(b"#c071fe")),
    ("light yellow green", Rgba8::from_hex(b"#ccfd7f")),
    ("dark navy blue", Rgba8::from_hex(b"#00022e")),
    ("drab", Rgba8::from_hex(b"#828344")),
    ("light rose", Rgba8::from_hex(b"#ffc5cb")),
    ("rouge", Rgba8::from_hex(b"#ab1239")),
    ("purplish red", Rgba8::from_hex(b"#b0054b")),
    ("slime green", Rgba8::from_hex(b"#99cc04")),
    ("baby poop", Rgba8::from_hex(b"#937c00")),
    ("irish green", Rgba8::from_hex(b"#019529")),
    ("pink/purple", Rgba8::from_hex(b"#ef1de7")),
    ("dark navy", Rgba8::from_hex(b"#000435")),
    ("greeny blue", Rgba8::from_hex(b"#42b395")),
    ("light plum", Rgba8::from_hex(b"#9d5783")),
    ("pinkish grey", Rgba8::from_hex(b"#c8aca9")),
    ("dirty orange", Rgba8::from_hex(b"#c87606")),
    ("rust red", Rgba8::from_hex(b"#aa2704")),
    ("pale lilac", Rgba8::from_hex(b"#e4cbff")),
    ("orangey red", Rgba8::from_hex(b"#fa4224")),
    ("primary blue", Rgba8::from_hex(b"#0804f9")),
    ("kermit green", Rgba8::from_hex(b"#5cb200")),
    ("brownish purple", Rgba8::from_hex(b"#76424e")),
    ("murky green", Rgba8::from_hex(b"#6c7a0e")),
    ("very dark purple", Rgba8::from_hex(b"#2a0134")),
    ("bottle green", Rgba8::from_hex(b"#044a05")),
    ("watermelon", Rgba8::from_hex(b"#fd4659")),
    ("deep sky blue", Rgba8::from_hex(b"#0d75f8")),
    ("fire engine red", Rgba8::from_hex(b"#fe0002")),
    ("yellow ochre", Rgba8::from_hex(b"#cb9d06")),
    ("pumpkin orange", Rgba8::from_hex(b"#fb7d07")),
    ("pale olive", Rgba8::from_hex(b"#b9cc81")),
    ("light lilac", Rgba8::from_hex(b"#edc8ff")),
    ("lightish green", Rgba8::from_hex(b"#61e160")),
    ("carolina blue", Rgba8::from_hex(b"#8ab8fe")),
    ("mulberry", Rgba8::from_hex(b"#920a4e")),
    ("shocking pink", Rgba8::from_hex(b"#fe02a2")),
    ("auburn", Rgba8::from_hex(b"#9a3001")),
    ("bright lime green", Rgba8::from_hex(b"#65fe08")),
    ("celadon", Rgba8::from_hex(b"#befdb7")),
    ("pinkish brown", Rgba8::from_hex(b"#b17261")),
    ("poo brown", Rgba8::from_hex(b"#885f01")),
    ("bright sky blue", Rgba8::from_hex(b"#02ccfe")),
    ("celery", Rgba8::from_hex(b"#c1fd95")),
    ("dirt brown", Rgba8::from_hex(b"#836539")),
    ("strawberry", Rgba8::from_hex(b"#fb2943")),
    ("dark lime", Rgba8::from_hex(b"#84b701")),
    ("copper", Rgba8::from_hex(b"#b66325")),
    ("medium brown", Rgba8::from_hex(b"#7f5112")),
    ("muted green", Rgba8::from_hex(b"#5fa052")),
    ("robin's egg", Rgba8::from_hex(b"#6dedfd")),
    ("bright aqua", Rgba8::from_hex(b"#0bf9ea")),
    ("bright lavender", Rgba8::from_hex(b"#c760ff")),
    ("very light purple", Rgba8::from_hex(b"#f6cefc")),
    ("light navy", Rgba8::from_hex(b"#155084")),
    ("pink red", Rgba8::from_hex(b"#f5054f")),
    ("olive brown", Rgba8::from_hex(b"#645403")),
    ("poop brown", Rgba8::from_hex(b"#7a5901")),
    ("mustard green", Rgba8::from_hex(b"#a8b504")),
    ("ocean green", Rgba8::from_hex(b"#3d9973")),
    ("very dark blue", Rgba8::from_hex(b"#000133")),
    ("dusty green", Rgba8::from_hex(b"#76a973")),
    ("light navy blue", Rgba8::from_hex(b"#2e5a88")),
    ("minty green", Rgba8::from_hex(b"#0bf77d")),
    ("adobe", Rgba8::from_hex(b"#bd6c48")),
    ("barney", Rgba8::from_hex(b"#ac1db8")),
    ("jade green", Rgba8::from_hex(b"#2baf6a")),
    ("bright light blue", Rgba8::from_hex(b"#26f7fd")),
    ("light lime", Rgba8::from_hex(b"#aefd6c")),
    ("dark khaki", Rgba8::from_hex(b"#9b8f55")),
    ("orange yellow", Rgba8::from_hex(b"#ffad01")),
    ("ocre", Rgba8::from_hex(b"#c69c04")),
    ("maize", Rgba8::from_hex(b"#f4d054")),
    ("faded pink", Rgba8::from_hex(b"#de9dac")),
    ("british racing green", Rgba8::from_hex(b"#05480d")),
    ("sandstone", Rgba8::from_hex(b"#c9ae74")),
    ("mud brown", Rgba8::from_hex(b"#60460f")),
    ("light sea green", Rgba8::from_hex(b"#98f6b0")),
    ("robin egg blue", Rgba8::from_hex(b"#8af1fe")),
    ("aqua marine", Rgba8::from_hex(b"#2ee8bb")),
    ("dark sea green", Rgba8::from_hex(b"#11875d")),
    ("soft pink", Rgba8::from_hex(b"#fdb0c0")),
    ("orangey brown", Rgba8::from_hex(b"#b16002")),
    ("cherry red", Rgba8::from_hex(b"#f7022a")),
    ("burnt yellow", Rgba8::from_hex(b"#d5ab09")),
    ("brownish grey", Rgba8::from_hex(b"#86775f")),
    ("camel", Rgba8::from_hex(b"#c69f59")),
    ("purplish grey", Rgba8::from_hex(b"#7a687f")),
    ("marine", Rgba8::from_hex(b"#042e60")),
    ("greyish pink", Rgba8::from_hex(b"#c88d94")),
    ("pale turquoise", Rgba8::from_hex(b"#a5fbd5")),
    ("pastel yellow", Rgba8::from_hex(b"#fffe71")),
    ("bluey purple", Rgba8::from_hex(b"#6241c7")),
    ("canary yellow", Rgba8::from_hex(b"#fffe40")),
    ("faded red", Rgba8::from_hex(b"#d3494e")),
    ("sepia", Rgba8::from_hex(b"#985e2b")),
    ("coffee", Rgba8::from_hex(b"#a6814c")),
    ("bright magenta", Rgba8::from_hex(b"#ff08e8")),
    ("mocha", Rgba8::from_hex(b"#9d7651")),
    ("ecru", Rgba8::from_hex(b"#feffca")),
    ("purpleish", Rgba8::from_hex(b"#98568d")),
    ("cranberry", Rgba8::from_hex(b"#9e003a")),
    ("darkish green", Rgba8::from_hex(b"#287c37")),
    ("brown orange", Rgba8::from_hex(b"#b96902")),
    ("dusky rose", Rgba8::from_hex(b"#ba6873")),
    ("melon", Rgba8::from_hex(b"#ff7855")),
    ("sickly green", Rgba8::from_hex(b"#94b21c")),
    ("purply blue", Rgba8::from_hex(b"#661aee")),
    ("purpleish blue", Rgba8::from_hex(b"#6140ef")),
    ("hospital green", Rgba8::from_hex(b"#9be5aa")),
    ("shit brown", Rgba8::from_hex(b"#7b5804")),
    ("mid blue", Rgba8::from_hex(b"#276ab3")),
    ("amber", Rgba8::from_hex(b"#feb308")),
    ("easter green", Rgba8::from_hex(b"#8cfd7e")),
    ("soft blue", Rgba8::from_hex(b"#6488ea")),
    ("cerulean blue", Rgba8::from_hex(b"#056eee")),
    ("golden brown", Rgba8::from_hex(b"#b27a01")),
    ("bright turquoise", Rgba8::from_hex(b"#0ffef9")),
    ("red pink", Rgba8::from_hex(b"#fa2a55")),
    ("red purple", Rgba8::from_hex(b"#820747")),
    ("greyish brown", Rgba8::from_hex(b"#7a6a4f")),
    ("vermillion", Rgba8::from_hex(b"#f4320c")),
    ("russet", Rgba8::from_hex(b"#a13905")),
    ("steel grey", Rgba8::from_hex(b"#6f828a")),
    ("lighter purple", Rgba8::from_hex(b"#a55af4")),
    ("bright violet", Rgba8::from_hex(b"#ad0afd")),
    ("prussian blue", Rgba8::from_hex(b"#004577")),
    ("slate green", Rgba8::from_hex(b"#658d6d")),
    ("dirty pink", Rgba8::from_hex(b"#ca7b80")),
    ("dark blue green", Rgba8::from_hex(b"#005249")),
    ("pine", Rgba8::from_hex(b"#2b5d34")),
    ("yellowy green", Rgba8::from_hex(b"#bff128")),
    ("dark gold", Rgba8::from_hex(b"#b59410")),
    ("bluish", Rgba8::from_hex(b"#2976bb")),
    ("darkish blue", Rgba8::from_hex(b"#014182")),
    ("dull red", Rgba8::from_hex(b"#bb3f3f")),
    ("pinky red", Rgba8::from_hex(b"#fc2647")),
    ("bronze", Rgba8::from_hex(b"#a87900")),
    ("pale teal", Rgba8::from_hex(b"#82cbb2")),
    ("military green", Rgba8::from_hex(b"#667c3e")),
    ("barbie pink", Rgba8::from_hex(b"#fe46a5")),
    ("bubblegum pink", Rgba8::from_hex(b"#fe83cc")),
    ("pea soup green", Rgba8::from_hex(b"#94a617")),
    ("dark mustard", Rgba8::from_hex(b"#a88905")),
    ("shit", Rgba8::from_hex(b"#7f5f00")),
    ("medium purple", Rgba8::from_hex(b"#9e43a2")),
    ("very dark green", Rgba8::from_hex(b"#062e03")),
    ("dirt", Rgba8::from_hex(b"#8a6e45")),
    ("dusky pink", Rgba8::from_hex(b"#cc7a8b")),
    ("red violet", Rgba8::from_hex(b"#9e0168")),
    ("lemon yellow", Rgba8::from_hex(b"#fdff38")),
    ("pistachio", Rgba8::from_hex(b"#c0fa8b")),
    ("dull yellow", Rgba8::from_hex(b"#eedc5b")),
    ("dark lime green", Rgba8::from_hex(b"#7ebd01")),
    ("denim blue", Rgba8::from_hex(b"#3b5b92")),
    ("teal blue", Rgba8::from_hex(b"#01889f")),
    ("lightish blue", Rgba8::from_hex(b"#3d7afd")),
    ("purpley blue", Rgba8::from_hex(b"#5f34e7")),
    ("light indigo", Rgba8::from_hex(b"#6d5acf")),
    ("swamp green", Rgba8::from_hex(b"#748500")),
    ("brown green", Rgba8::from_hex(b"#706c11")),
    ("dark maroon", Rgba8::from_hex(b"#3c0008")),
    ("hot purple", Rgba8::from_hex(b"#cb00f5")),
    ("dark forest green", Rgba8::from_hex(b"#002d04")),
    ("faded blue", Rgba8::from_hex(b"#658cbb")),
    ("drab green", Rgba8::from_hex(b"#749551")),
    ("light lime green", Rgba8::from_hex(b"#b9ff66")),
    ("snot green", Rgba8::from_hex(b"#9dc100")),
    ("yellowish", Rgba8::from_hex(b"#faee66")),
    ("light blue green", Rgba8::from_hex(b"#7efbb3")),
    ("bordeaux", Rgba8::from_hex(b"#7b002c")),
    ("light mauve", Rgba8::from_hex(b"#c292a1")),
    ("ocean", Rgba8::from_hex(b"#017b92")),
    ("marigold", Rgba8::from_hex(b"#fcc006")),
    ("muddy green", Rgba8::from_hex(b"#657432")),
    ("dull orange", Rgba8::from_hex(b"#d8863b")),
    ("steel", Rgba8::from_hex(b"#738595")),
    ("electric purple", Rgba8::from_hex(b"#aa23ff")),
    ("fluorescent green", Rgba8::from_hex(b"#08ff08")),
    ("yellowish brown", Rgba8::from_hex(b"#9b7a01")),
    ("blush", Rgba8::from_hex(b"#f29e8e")),
    ("soft green", Rgba8::from_hex(b"#6fc276")),
    ("bright orange", Rgba8::from_hex(b"#ff5b00")),
    ("lemon", Rgba8::from_hex(b"#fdff52")),
    ("purple grey", Rgba8::from_hex(b"#866f85")),
    ("acid green", Rgba8::from_hex(b"#8ffe09")),
    ("pale lavender", Rgba8::from_hex(b"#eecffe")),
    ("violet blue", Rgba8::from_hex(b"#510ac9")),
    ("light forest green", Rgba8::from_hex(b"#4f9153")),
    ("burnt red", Rgba8::from_hex(b"#9f2305")),
    ("khaki green", Rgba8::from_hex(b"#728639")),
    ("cerise", Rgba8::from_hex(b"#de0c62")),
    ("faded purple", Rgba8::from_hex(b"#916e99")),
    ("apricot", Rgba8::from_hex(b"#ffb16d")),
    ("dark olive green", Rgba8::from_hex(b"#3c4d03")),
    ("grey brown", Rgba8::from_hex(b"#7f7053")),
    ("green grey", Rgba8::from_hex(b"#77926f")),
    ("true blue", Rgba8::from_hex(b"#010fcc")),
    ("pale violet", Rgba8::from_hex(b"#ceaefa")),
    ("periwinkle blue", Rgba8::from_hex(b"#8f99fb")),
    ("light sky blue", Rgba8::from_hex(b"#c6fcff")),
    ("blurple", Rgba8::from_hex(b"#5539cc")),
    ("green brown", Rgba8::from_hex(b"#544e03")),
    ("bluegreen", Rgba8::from_hex(b"#017a79")),
    ("bright teal", Rgba8::from_hex(b"#01f9c6")),
    ("brownish yellow", Rgba8::from_hex(b"#c9b003")),
    ("pea soup", Rgba8::from_hex(b"#929901")),
    ("forest", Rgba8::from_hex(b"#0b5509")),
    ("barney purple", Rgba8::from_hex(b"#a00498")),
    ("ultramarine", Rgba8::from_hex(b"#2000b1")),
    ("purplish", Rgba8::from_hex(b"#94568c")),
    ("puke yellow", Rgba8::from_hex(b"#c2be0e")),
    ("bluish grey", Rgba8::from_hex(b"#748b97")),
    ("dark periwinkle", Rgba8::from_hex(b"#665fd1")),
    ("dark lilac", Rgba8::from_hex(b"#9c6da5")),
    ("reddish", Rgba8::from_hex(b"#c44240")),
    ("light maroon", Rgba8::from_hex(b"#a24857")),
    ("dusty purple", Rgba8::from_hex(b"#825f87")),
    ("terra cotta", Rgba8::from_hex(b"#c9643b")),
    ("avocado", Rgba8::from_hex(b"#90b134")),
    ("marine blue", Rgba8::from_hex(b"#01386a")),
    ("teal green", Rgba8::from_hex(b"#25a36f")),
    ("slate grey", Rgba8::from_hex(b"#59656d")),
    ("lighter green", Rgba8::from_hex(b"#75fd63")),
    ("electric green", Rgba8::from_hex(b"#21fc0d")),
    ("dusty blue", Rgba8::from_hex(b"#5a86ad")),
    ("golden yellow", Rgba8::from_hex(b"#fec615")),
    ("bright yellow", Rgba8::from_hex(b"#fffd01")),
    ("light lavender", Rgba8::from_hex(b"#dfc5fe")),
    ("umber", Rgba8::from_hex(b"#b26400")),
    ("poop", Rgba8::from_hex(b"#7f5e00")),
    ("dark peach", Rgba8::from_hex(b"#de7e5d")),
    ("jungle green", Rgba8::from_hex(b"#048243")),
    ("eggshell", Rgba8::from_hex(b"#ffffd4")),
    ("denim", Rgba8::from_hex(b"#3b638c")),
    ("yellow brown", Rgba8::from_hex(b"#b79400")),
    ("dull purple", Rgba8::from_hex(b"#84597e")),
    ("chocolate brown", Rgba8::from_hex(b"#411900")),
    ("wine red", Rgba8::from_hex(b"#7b0323")),
    ("neon blue", Rgba8::from_hex(b"#04d9ff")),
    ("dirty green", Rgba8::from_hex(b"#667e2c")),
    ("light tan", Rgba8::from_hex(b"#fbeeac")),
    ("ice blue", Rgba8::from_hex(b"#d7fffe")),
    ("cadet blue", Rgba8::from_hex(b"#4e7496")),
    ("dark mauve", Rgba8::from_hex(b"#874c62")),
    ("very light blue", Rgba8::from_hex(b"#d5ffff")),
    ("grey purple", Rgba8::from_hex(b"#826d8c")),
    ("pastel pink", Rgba8::from_hex(b"#ffbacd")),
    ("very light green", Rgba8::from_hex(b"#d1ffbd")),
    ("dark sky blue", Rgba8::from_hex(b"#448ee4")),
    ("evergreen", Rgba8::from_hex(b"#05472a")),
    ("dull pink", Rgba8::from_hex(b"#d5869d")),
    ("aubergine", Rgba8::from_hex(b"#3d0734")),
    ("mahogany", Rgba8::from_hex(b"#4a0100")),
    ("reddish orange", Rgba8::from_hex(b"#f8481c")),
    ("deep green", Rgba8::from_hex(b"#02590f")),
    ("vomit green", Rgba8::from_hex(b"#89a203")),
    ("purple pink", Rgba8::from_hex(b"#e03fd8")),
    ("dusty pink", Rgba8::from_hex(b"#d58a94")),
    ("faded green", Rgba8::from_hex(b"#7bb274")),
    ("camo green", Rgba8::from_hex(b"#526525")),
    ("pinky purple", Rgba8::from_hex(b"#c94cbe")),
    ("pink purple", Rgba8::from_hex(b"#db4bda")),
    ("brownish red", Rgba8::from_hex(b"#9e3623")),
    ("dark rose", Rgba8::from_hex(b"#b5485d")),
    ("mud", Rgba8::from_hex(b"#735c12")),
    ("brownish", Rgba8::from_hex(b"#9c6d57")),
    ("emerald green", Rgba8::from_hex(b"#028f1e")),
    ("pale brown", Rgba8::from_hex(b"#b1916e")),
    ("dull blue", Rgba8::from_hex(b"#49759c")),
    ("burnt umber", Rgba8::from_hex(b"#a0450e")),
    ("medium green", Rgba8::from_hex(b"#39ad48")),
    ("clay", Rgba8::from_hex(b"#b66a50")),
    ("light aqua", Rgba8::from_hex(b"#8cffdb")),
    ("light olive green", Rgba8::from_hex(b"#a4be5c")),
    ("brownish orange", Rgba8::from_hex(b"#cb7723")),
    ("dark aqua", Rgba8::from_hex(b"#05696b")),
    ("purplish pink", Rgba8::from_hex(b"#ce5dae")),
    ("dark salmon", Rgba8::from_hex(b"#c85a53")),
    ("greenish grey", Rgba8::from_hex(b"#96ae8d")),
    ("jade", Rgba8::from_hex(b"#1fa774")),
    ("ugly green", Rgba8::from_hex(b"#7a9703")),
    ("dark beige", Rgba8::from_hex(b"#ac9362")),
    ("emerald", Rgba8::from_hex(b"#01a049")),
    ("pale red", Rgba8::from_hex(b"#d9544d")),
    ("light magenta", Rgba8::from_hex(b"#fa5ff7")),
    ("sky", Rgba8::from_hex(b"#82cafc")),
    ("light cyan", Rgba8::from_hex(b"#acfffc")),
    ("yellow orange", Rgba8::from_hex(b"#fcb001")),
    ("reddish purple", Rgba8::from_hex(b"#910951")),
    ("reddish pink", Rgba8::from_hex(b"#fe2c54")),
    ("dirty yellow", Rgba8::from_hex(b"#cdc50a")),
    ("orange red", Rgba8::from_hex(b"#fd411e")),
    ("deep red", Rgba8::from_hex(b"#9a0200")),
    ("orange brown", Rgba8::from_hex(b"#be6400")),
    ("cobalt blue", Rgba8::from_hex(b"#030aa7")),
    ("neon pink", Rgba8::from_hex(b"#fe019a")),
    ("rose pink", Rgba8::from_hex(b"#f7879a")),
    ("greyish purple", Rgba8::from_hex(b"#887191")),
    ("raspberry", Rgba8::from_hex(b"#b00149")),
    ("aqua green", Rgba8::from_hex(b"#12e193")),
    ("salmon pink", Rgba8::from_hex(b"#fe7b7c")),
    ("tangerine", Rgba8::from_hex(b"#ff9408")),
    ("brownish green", Rgba8::from_hex(b"#6a6e09")),
    ("red brown", Rgba8::from_hex(b"#8b2e16")),
    ("greenish brown", Rgba8::from_hex(b"#696112")),
    ("pumpkin", Rgba8::from_hex(b"#e17701")),
    ("pine green", Rgba8::from_hex(b"#0a481e")),
    ("charcoal", Rgba8::from_hex(b"#343837")),
    ("baby pink", Rgba8::from_hex(b"#ffb7ce")),
    ("cornflower", Rgba8::from_hex(b"#6a79f7")),
    ("blue violet", Rgba8::from_hex(b"#5d06e9")),
    ("greyish green", Rgba8::from_hex(b"#82a67d")),
    ("scarlet", Rgba8::from_hex(b"#be0119")),
    ("green yellow", Rgba8::from_hex(b"#c9ff27")),
    ("dark olive", Rgba8::from_hex(b"#373e02")),
    ("pastel purple", Rgba8::from_hex(b"#caa0ff")),
    ("terracotta", Rgba8::from_hex(b"#ca6641")),
    ("aqua blue", Rgba8::from_hex(b"#02d8e9")),
    ("sage green", Rgba8::from_hex(b"#88b378")),
    ("blood red", Rgba8::from_hex(b"#980002")),
    ("deep pink", Rgba8::from_hex(b"#cb0162")),
    ("grass", Rgba8::from_hex(b"#5cac2d")),
    ("moss", Rgba8::from_hex(b"#769958")),
    ("pastel blue", Rgba8::from_hex(b"#a2bffe")),
    ("bluish green", Rgba8::from_hex(b"#10a674")),
    ("green blue", Rgba8::from_hex(b"#06b48b")),
    ("dark tan", Rgba8::from_hex(b"#af884a")),
    ("greenish blue", Rgba8::from_hex(b"#0b8b87")),
    ("pale orange", Rgba8::from_hex(b"#ffa756")),
    ("vomit", Rgba8::from_hex(b"#a2a415")),
    ("forrest green", Rgba8::from_hex(b"#154406")),
    ("dark lavender", Rgba8::from_hex(b"#856798")),
    ("dark violet", Rgba8::from_hex(b"#34013f")),
    ("purple blue", Rgba8::from_hex(b"#632de9")),
    ("dark cyan", Rgba8::from_hex(b"#0a888a")),
    ("olive drab", Rgba8::from_hex(b"#6f7632")),
    ("pinkish", Rgba8::from_hex(b"#d46a7e")),
    ("cobalt", Rgba8::from_hex(b"#1e488f")),
    ("neon purple", Rgba8::from_hex(b"#bc13fe")),
    ("light turquoise", Rgba8::from_hex(b"#7ef4cc")),
    ("apple green", Rgba8::from_hex(b"#76cd26")),
    ("dull green", Rgba8::from_hex(b"#74a662")),
    ("wine", Rgba8::from_hex(b"#80013f")),
    ("powder blue", Rgba8::from_hex(b"#b1d1fc")),
    ("off white", Rgba8::from_hex(b"#ffffe4")),
    ("electric blue", Rgba8::from_hex(b"#0652ff")),
    ("dark turquoise", Rgba8::from_hex(b"#045c5a")),
    ("blue purple", Rgba8::from_hex(b"#5729ce")),
    ("bright red", Rgba8::from_hex(b"#ff000d")),
    ("pinkish red", Rgba8::from_hex(b"#f10c45")),
    ("cornflower blue", Rgba8::from_hex(b"#5170d7")),
    ("light olive", Rgba8::from_hex(b"#acbf69")),
    ("grape", Rgba8::from_hex(b"#6c3461")),
    ("greyish blue", Rgba8::from_hex(b"#5e819d")),
    ("purplish blue", Rgba8::from_hex(b"#601ef9")),
    ("yellowish green", Rgba8::from_hex(b"#b0dd16")),
    ("greenish yellow", Rgba8::from_hex(b"#cdfd02")),
    ("medium blue", Rgba8::from_hex(b"#2c6fbb")),
    ("dusty rose", Rgba8::from_hex(b"#c0737a")),
    ("light violet", Rgba8::from_hex(b"#d6b4fc")),
    ("midnight blue", Rgba8::from_hex(b"#020035")),
    ("bluish purple", Rgba8::from_hex(b"#703be7")),
    ("red orange", Rgba8::from_hex(b"#fd3c06")),
    ("dark magenta", Rgba8::from_hex(b"#960056")),
    ("greenish", Rgba8::from_hex(b"#40a368")),
    ("ocean blue", Rgba8::from_hex(b"#03719c")),
    ("cream", Rgba8::from_hex(b"#ffffc2")),
    ("reddish brown", Rgba8::from_hex(b"#7f2b0a")),
    ("burnt sienna", Rgba8::from_hex(b"#b04e0f")),
    ("brick", Rgba8::from_hex(b"#a03623")),
    ("sage", Rgba8::from_hex(b"#87ae73")),
    ("grey green", Rgba8::from_hex(b"#789b73")),
    ("robin's egg blue", Rgba8::from_hex(b"#98eff9")),
    ("moss green", Rgba8::from_hex(b"#658b38")),
    ("steel blue", Rgba8::from_hex(b"#5a7d9a")),
    ("eggplant", Rgba8::from_hex(b"#380835")),
    ("light yellow", Rgba8::from_hex(b"#fffe7a")),
    ("leaf green", Rgba8::from_hex(b"#5ca904")),
    ("light grey", Rgba8::from_hex(b"#d8dcd6")),
    ("puke", Rgba8::from_hex(b"#a5a502")),
    ("pinkish purple", Rgba8::from_hex(b"#d648d7")),
    ("sea blue", Rgba8::from_hex(b"#047495")),
    ("pale purple", Rgba8::from_hex(b"#b790d4")),
    ("slate blue", Rgba8::from_hex(b"#5b7c99")),
    ("blue grey", Rgba8::from_hex(b"#607c8e")),
    ("hunter green", Rgba8::from_hex(b"#0b4008")),
    ("pale yellow", Rgba8::from_hex(b"#ffff84")),
    ("ochre", Rgba8::from_hex(b"#bf9005")),
    ("mustard yellow", Rgba8::from_hex(b"#d2bd0a")),
    ("light red", Rgba8::from_hex(b"#ff474c")),
    ("cerulean", Rgba8::from_hex(b"#0485d1")),
    ("pale pink", Rgba8::from_hex(b"#ffcfdc")),
    ("deep blue", Rgba8::from_hex(b"#040273")),
    ("rust", Rgba8::from_hex(b"#a83c09")),
    ("light teal", Rgba8::from_hex(b"#90e4c1")),
    ("slate", Rgba8::from_hex(b"#516572")),
    ("dark yellow", Rgba8::from_hex(b"#d5b60a")),
    ("dark grey", Rgba8::from_hex(b"#363737")),
    ("army green", Rgba8::from_hex(b"#4b5d16")),
    ("grey blue", Rgba8::from_hex(b"#6b8ba4")),
    ("seafoam", Rgba8::from_hex(b"#80f9ad")),
    ("puce", Rgba8::from_hex(b"#a57e52")),
    ("spring green", Rgba8::from_hex(b"#a9f971")),
    ("dark orange", Rgba8::from_hex(b"#c65102")),
    ("sand", Rgba8::from_hex(b"#e2ca76")),
    ("pastel green", Rgba8::from_hex(b"#b0ff9d")),
    ("mint", Rgba8::from_hex(b"#9ffeb0")),
    ("light orange", Rgba8::from_hex(b"#fdaa48")),
    ("bright pink", Rgba8::from_hex(b"#fe01b1")),
    ("deep purple", Rgba8::from_hex(b"#36013f")),
    ("dark brown", Rgba8::from_hex(b"#341c02")),
    ("taupe", Rgba8::from_hex(b"#b9a281")),
    ("pea green", Rgba8::from_hex(b"#8eab12")),
    ("puke green", Rgba8::from_hex(b"#9aae07")),
    ("kelly green", Rgba8::from_hex(b"#02ab2e")),
    ("seafoam green", Rgba8::from_hex(b"#7af9ab")),
    ("blue green", Rgba8::from_hex(b"#137e6d")),
    ("burgundy", Rgba8::from_hex(b"#610023")),
    ("dark teal", Rgba8::from_hex(b"#014d4e")),
    ("brick red", Rgba8::from_hex(b"#8f1402")),
    ("royal purple", Rgba8::from_hex(b"#4b006e")),
    ("mint green", Rgba8::from_hex(b"#8fff9f")),
    ("baby blue", Rgba8::from_hex(b"#a2cffe")),
    ("yellow green", Rgba8::from_hex(b"#c0fb2d")),
    ("bright purple", Rgba8::from_hex(b"#be03fd")),
    ("dark red", Rgba8::from_hex(b"#840000")),
    ("pale blue", Rgba8::from_hex(b"#d0fefe")),
    ("grass green", Rgba8::from_hex(b"#3f9b0b")),
    ("burnt orange", Rgba8::from_hex(b"#c04e01")),
    ("neon green", Rgba8::from_hex(b"#0cff0c")),
    ("bright blue", Rgba8::from_hex(b"#0165fc")),
    ("rose", Rgba8::from_hex(b"#cf6275")),
    ("light pink", Rgba8::from_hex(b"#ffd1df")),
    ("mustard", Rgba8::from_hex(b"#ceb301")),
    ("sea green", Rgba8::from_hex(b"#53fca1")),
    ("periwinkle", Rgba8::from_hex(b"#8e82fe")),
    ("dark pink", Rgba8::from_hex(b"#cb416b")),
    ("olive green", Rgba8::from_hex(b"#677a04")),
    ("peach", Rgba8::from_hex(b"#ffb07c")),
    ("pale green", Rgba8::from_hex(b"#c7fdb5")),
    ("light brown", Rgba8::from_hex(b"#ad8150")),
    ("hot pink", Rgba8::from_hex(b"#ff028d")),
    ("lilac", Rgba8::from_hex(b"#cea2fd")),
    ("navy blue", Rgba8::from_hex(b"#001146")),
    ("royal blue", Rgba8::from_hex(b"#0504aa")),
    ("bright green", Rgba8::from_hex(b"#01ff07")),
    ("dark purple", Rgba8::from_hex(b"#35063e")),
    ("mauve", Rgba8::from_hex(b"#ae7181")),
    ("forest green", Rgba8::from_hex(b"#06470c")),
    ("dark blue", Rgba8::from_hex(b"#00035b")),
    ("dark green", Rgba8::from_hex(b"#033500")),
    ("light purple", Rgba8::from_hex(b"#bf77f6")),
    ("lime green", Rgba8::from_hex(b"#89fe05")),
    ("sky blue", Rgba8::from_hex(b"#75bbfd")),
    ("light green", Rgba8::from_hex(b"#96f97b")),
    ("light blue", Rgba8::from_hex(b"#95d0fc")),
];
