[package]
name = "plotive"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
plotive-base.workspace = true
plotive-text.workspace = true
# feature dsl
plotive-dsl = { workspace = true, optional = true }

[dev-dependencies]
plotive-iced = { path = "iced", features = ["clipboard"] }
plotive-svg = { path = "svg" }
plotive-pxl = { path = "pxl" }
rand.workspace = true
rand_distr.workspace = true
rand_chacha.workspace = true
ode_solvers = "0.6.1"

[features]
default = ["noto-sans"]

data-csv = []
dsl = ["plotive-dsl/diag"]
noto-mono = ["plotive-text/noto-mono"]
noto-sans = ["plotive-text/noto-sans"]
noto-sans-italic = ["plotive-text/noto-sans-italic"]
noto-serif = ["plotive-text/noto-serif"]
noto-serif-italic = ["plotive-text/noto-serif-italic"]
time = []
utils = []

[[example]]
name = "area"

[[example]]
name = "bars"

[[example]]
name = "bitcoin"
required-features = ["data-csv", "time"]

[[example]]
name = "bode_rlc"
required-features = ["noto-serif-italic", "utils"]

[[example]]
name = "bode_rlc_dsl"
required-features = ["dsl", "noto-serif-italic", "utils"]

[[example]]
name = "bouncing_ball"
required-features = ["time"]

[[example]]
name = "gauss"

[[example]]
name = "iris"
required-features = ["data-csv"]

[[example]]
name = "iris_dsl"
required-features = ["data-csv", "dsl"]

[[example]]
name = "multiple_axes"
required-features = ["utils"]

[[example]]
name = "multiple_axes_dsl"
required-features = ["dsl", "utils"]

[[example]]
name = "readme"

[[example]]
name = "sine"

[[example]]
name = "stars"
required-features = ["data-csv"]

[[example]]
name = "subplots"
required-features = ["utils"]

[[example]]
name = "subplots_dsl"
required-features = ["dsl", "utils"]

[workspace]
members = ["base", "dsl", "iced", "pxl", "svg", "text", "tests"]
resolver = "3"

[workspace.package]
version = "0.4.0"
authors = ["Rémi THEBAULT"]
description = "Simple data plotting library"
edition = "2024"
repository = "https://github.com/rtbo/plotive"
license = "MIT"
categories = ["science", "graphics"]
keywords = ["data", "visualization", "plotting"]

[workspace.dependencies]
plotive = { version = "0.4.0", path = "." }
plotive-base = { version = "0.4.0", path = "base" }
plotive-dsl = { version = "0.4.0", path = "dsl" }
plotive-iced = { version = "0.4.0", path = "iced" }
plotive-pxl = { version = "0.4.0", path = "pxl" }
plotive-svg = { version = "0.4.0", path = "svg" }
plotive-text = { version = "0.4.0", path = "text" }
arboard = "3.6.1"
bytes = "1.6"
iced = { version = "0.14.0", features = [
    "advanced",
    "canvas",
    "image",
    "tokio",
] }
iced_font_awesome = "0.4.0"
log = "0.4"
miette = { version = "7.6.0", features = ["fancy"] }
rand = "0.9.2"
rand_distr = "0.5.1"
rand_chacha = "0.9.0"
rfd = "0.17.1"
rustybuzz = "0.20.1"
strict-num = "0.2.0"
tiny-skia = "0.11.4"
tiny-skia-path = "0.11.4"
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "time"] }

[workspace.dependencies.ttf-parser]
version = "0.25.1"
default-features = false
features = [
    "opentype-layout",
    "apple-layout",
    "variable-fonts",
    "glyph-names",
    "no-std-float",
]
